"""empty message

Revision ID: 3840a0fb6f85
Revises: c816d8d96989
Create Date: 2025-10-16 00:25:49.459253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3840a0fb6f85'
down_revision = 'c816d8d96989'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
